import JSZip from "jszip";

export type ReleasePackageInput = {
  version: string;
  releaseEndpoint: string;
  sdkUrl: string | null;
  manifest: Record<string, unknown>;
  migrations: Array<Record<string, unknown>>;
  changelog?: string | null;
  minCompatibleChild?: string | null;
};

export type ReleasePackageMeta = {
  blob: Blob;
  sha256: string;
  size: number;
};

async function sha256Hex(blob: Blob): Promise<string> {
  const buf = await blob.arrayBuffer();
  const hash = await crypto.subtle.digest("SHA-256", buf);
  return Array.from(new Uint8Array(hash)).map((b) => b.toString(16).padStart(2, "0")).join("");
}

function stableJson(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

export async function buildReleaseZip(input: ReleasePackageInput): Promise<ReleasePackageMeta> {
  const zip = new JSZip();
  const releaseJson = {
    version: input.version,
    releaseEndpoint: input.releaseEndpoint,
    sdkUrl: input.sdkUrl,
    minCompatibleChild: input.minCompatibleChild ?? null,
    changelog: input.changelog ?? null,
    generatedAt: new Date().toISOString(),
  };

  zip.file("README.md", `# Parent CMS v${input.version}\n\nThis ZIP is an installable CMS release package generated by the parent CMS.\n\n## Install with ZIP\n\n1. Unzip this package into the child project.\n2. Copy \`cms-bootstrap.example.ts\` into your app entry flow.\n3. Add the values from \`.env.example\` to the child environment.\n4. Register one catch-all route that renders your dynamic page router.\n\n## Install with Bun or npm from this ZIP\n\n\`\`\`bash\ncd parentcms-client\nbun install\nbun run build\n# or\nnpm install\nnpm run build\n\`\`\`\n\nThen import the local package from the child app:\n\n\`\`\`ts\nimport { ParentCMS } from \"./parentcms-client/src\";\n\`\`\`\n\n## Secure upgrades\n\nChild sites should fetch ${input.releaseEndpoint}, verify the signed release payload, apply migrations, and only then load the SDK URL.\n`);

  zip.file("release.json", stableJson(releaseJson));
  zip.file("manifest.json", stableJson(input.manifest));
  zip.file("migrations.json", stableJson(input.migrations));
  zip.file(".env.example", `VITE_PARENT_API=${input.releaseEndpoint.replace(/\/cms-release\/?$/, "/site-config")}\nVITE_PARENT_RELEASE_API=${input.releaseEndpoint}\nVITE_SITE_ID=your-child-site-id\n`);
  zip.file("cms-bootstrap.example.ts", `export async function bootParentCms() {\n  const releaseUrl = import.meta.env.VITE_PARENT_RELEASE_API;\n  const siteId = import.meta.env.VITE_SITE_ID;\n  const res = await fetch(`${"${releaseUrl}"}?site_id=${"${encodeURIComponent(siteId)}"}`, { cache: "no-store" });\n  if (!res.ok) throw new Error(`Parent CMS release failed: ${"${res.status}"}`);\n  const release = await res.json();\n  if (release?.sdk_url) await import(/* @vite-ignore */ release.sdk_url);\n  return release;\n}\n`);

  const pkg = zip.folder("parentcms-client")!;
  pkg.file("package.json", stableJson({
    name: "parentcms-client",
    version: input.version,
    private: true,
    type: "module",
    main: "src/index.ts",
    scripts: { build: "tsc --noEmit" },
    peerDependencies: { "@supabase/supabase-js": "^2.0.0" },
    devDependencies: { typescript: "^5.0.0" },
  }));
  pkg.file("src/index.ts", `const API = import.meta.env.VITE_PARENT_API as string;\nconst SITE = import.meta.env.VITE_SITE_ID as string;\n\nfunction post(action: string, body: Record<string, unknown>) {\n  return fetch(`${"${API}"}?action=${"${action}"}`, {\n    method: "POST",\n    headers: { "Content-Type": "application/json" },\n    body: JSON.stringify(body),\n  }).then((r) => r.json());\n}\n\nexport const ParentCMS = {\n  library: () => fetch(`${"${API}"}?action=library&site_id=${"${SITE}"}`).then((r) => r.json()),\n  asset: (kind: string, id: string) => fetch(`${"${API}"}?action=asset&kind=${"${kind}"}&id=${"${id}"}`).then((r) => r.json()),\n  preview: (kind: string, id: string) => `${"${API}"}?action=preview&kind=${"${kind}"}&id=${"${id}"}&site_id=${"${SITE}"}`,\n  import: (kind: string, id: string, mode: "link" | "fork" = "link") => post("import_asset", { site_id: SITE, kind, id, mode }),\n  publish: (payload: Record<string, unknown>) => post("publish_asset", { site_id: SITE, ...payload }),\n  dynamicPage: (path: string) => fetch(`${"${API}"}?action=dynamic_page&site_id=${"${SITE}"}&path=${"${encodeURIComponent(path)}"}`).then((r) => r.json()),\n  autoCompose: (payload: Record<string, unknown>) => post("auto_compose", { site_id: SITE, ...payload }),\n  forms: () => fetch(`${"${API}"}?action=forms&site_id=${"${SITE}"}`).then((r) => r.json()),\n  submitForm: (id: string, data: Record<string, unknown>) => post("form_submit", { site_id: SITE, form_id: id, data }),\n  saveOverlay: (fp: string, patch: Record<string, unknown>) => post("overlay_patch", { site_id: SITE, fp, patch }),\n};\n`);

  const blob = await zip.generateAsync({ type: "blob", compression: "DEFLATE", compressionOptions: { level: 6 } });
  return { blob, sha256: await sha256Hex(blob), size: blob.size };
}