import React from 'react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import DOMPurify from 'dompurify';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';

const sanitizeHtml = (html: string) =>
  DOMPurify.sanitize(html || '', {
    ADD_TAGS: ['style', 'iframe', 'script', 'link'],
    ADD_ATTR: ['target', 'scrolling', 'frameborder', 'allow', 'allowfullscreen', 'rel', 'href'],
    FORCE_BODY: true,
  });

interface ServicePageTemplateProps {
  page: any;
  branding: { primary: string; accent: string; font: string };
}

/**
 * ServicePageTemplate renders a premium service page.
 * It displays a hero section, a zig‑zag image/text layout, a process steps area,
 * and an FAQ accordion. All other injected navigation/footer snippets are omitted.
 */
export default function ServicePageTemplate({ page, branding }: ServicePageTemplateProps) {
  // Remove the unwanted "Generated by Content Snapshot Pro" block from the body
  const cleanedBody = (page.body || '').replace(/Generated by Content Snapshot Pro[\s\S]*?\)/g, '');

  // Dummy data for zig‑zag sections – replace with real content later
  const sections = [
    {
      title: 'Our Expertise',
      text: 'We provide end‑to‑end BREEAM assessment services, from preliminary analysis to certification.',
      image: page.featured_image_url,
    },
    {
      title: 'Why Choose Us',
      text: 'Our team holds accredited BREEAM assessor qualifications and a proven track record of sustainable projects.',
      image: page.featured_image_url,
    },
  ];

  // Dummy process steps – replace with actual data from CMS if available
  const processSteps = [
    { title: 'Initial Consultation', description: 'Understanding your project goals and sustainability requirements.' },
    { title: 'Pre‑Assessment', description: 'Site analysis and preliminary scoring.' },
    { title: 'Full Assessment', description: 'Detailed evaluation following BREEAM criteria.' },
    { title: 'Certification Support', description: 'Guidance through the certification submission process.' },
  ];

  // Dummy FAQs – replace with real FAQs later
  const faqs = [
    { question: 'What is BREEAM?', answer: 'BREEAM is a leading sustainability assessment method for buildings.' },
    { question: 'How long does the assessment take?', answer: 'Typical timelines range from 4‑8 weeks depending on project size.' },
  ];

  return (
    <div className="service-page">
      {/* Hero Section */}
      <section
        className="bg-slate-50 text-slate-900 py-16 px-6 border-b flex flex-col md:flex-row items-center justify-between"
        style={{ backgroundImage: `url(${page.featured_image_url})`, backgroundSize: 'cover' }}
      >
        <div className="max-w-2xl space-y-4 bg-white/80 p-6 rounded-lg">
          <h1 className="text-4xl md:text-5xl font-extrabold" style={{ color: branding.primary }}>
            {page.title}
          </h1>
          <p className="text-lg" dangerouslySetInnerHTML={{ __html: sanitizeHtml(cleanedBody) }} />
          <Button asChild className="mt-4" style={{ backgroundColor: branding.primary, color: '#111' }}>
            <Link to="/book-a-call">Book a Call</Link>
          </Button>
        </div>
      </section>

      {/* Zig‑zag Sections */}
      {sections.map((sec, idx) => (
        <section
          key={idx}
          className={`py-12 px-6 flex flex-col md:flex-row gap-8 items-center ${idx % 2 === 1 ? 'md:flex-row-reverse' : ''}`}
        >
          <div className="flex-1 space-y-4">
            <h2 className="text-3xl font-bold" style={{ color: branding.primary }}>
              {sec.title}
            </h2>
            <p className="text-base text-slate-700">{sec.text}</p>
          </div>
          {sec.image && (
            <div className="w-full md:w-[320px]">
              <img src={sec.image} alt={sec.title} className="rounded-2xl shadow-md" />
            </div>
          )}
        </section>
      ))}

      {/* Process Steps */}
      <section className="bg-slate-100 py-12 px-6">
        <div className="max-w-4xl mx-auto text-center space-y-6">
          <h2 className="text-3xl font-extrabold" style={{ color: branding.primary }}>
            Our Process
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {processSteps.map((step, i) => (
              <div key={i} className="p-4 bg-white rounded-lg shadow-sm">
                <h3 className="font-semibold" style={{ color: branding.primary }}>
                  {step.title}
                </h3>
                <p className="text-sm text-slate-600">{step.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ Accordion */}
      <section className="py-12 px-6">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-3xl font-extrabold mb-6 text-center" style={{ color: branding.primary }}>
            Frequently Asked Questions
          </h2>
          <Accordion type="single" collapsible>
            {faqs.map((faq, i) => (
              <AccordionItem key={i} value={`item-${i}`}>
                <AccordionTrigger>{faq.question}</AccordionTrigger>
                <AccordionContent>{faq.answer}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>
    </div>
  );
}
