#!/usr/bin/env node
/**
 * Copy reusable Child CMS source from the Parent repo (src/) into
 * cms-distribution/managed/src/cms-managed/. Parent-only screens and
 * fleet/release/signing/GitHub-credential code are explicitly excluded.
 *
 * cms-distribution/managed is the source of truth for distributed files —
 * this script keeps it in sync with Parent's working source until the
 * managed folder is fully decoupled.
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..", "..");
const srcRoot = path.join(repoRoot, "src");
const dstRoot = path.join(repoRoot, "cms-distribution", "managed", "src", "cms-managed");

// Parent-only files/dirs that must NEVER be distributed.
const EXCLUDE_FILES = new Set([
  "pages/admin/AdminReleases.tsx",
  "pages/admin/AdminInstallations.tsx",
  "pages/admin/AdminUpgradeLog.tsx",
  "pages/admin/AdminSigningKeys.tsx",
  "pages/admin/AdminApiRegistry.tsx",
  "pages/admin/AdminSetupWizard.tsx",
  "pages/admin/AdminSyncHub.tsx",
  "pages/admin/AdminSyncControl.tsx",
  "pages/admin/AdminSync.tsx",
  "lib/releaseBuilder.ts",
  "lib/releasePackage.ts",
  "lib/releaseSigning.ts",
  "lib/sdkUpload.ts",
  "lib/distribution.ts",
  "lib/manifest.ts",
  "lib/manifestBuilder.ts",
  "lib/parent.ts",
  "lib/apiRegistry.ts",
  "lib/syncControl.ts",
  "cms-child/RemoteAdmin.tsx",
  "admin-bundle/entry.tsx",
  "admin-bundle/supabase-runtime.ts",
]);

const EXCLUDE_DIRS = new Set([
  "admin-bundle",
  "cms-child",
  "cms-core",
]);

// Reusable trees to copy in their entirety (minus EXCLUDE_FILES / EXCLUDE_DIRS).
const INCLUDE_TREES = [
  "components/ui",
  "components/admin",
  "components/editor",
  "components/site",
  "components",
  "hooks",
  "lib",
  "pages/admin",
  "pages/admin/seo",
  "providers",
];

// Top-level reusable files.
const INCLUDE_FILES = [
  "index.css",
  "App.css",
];

async function rimraf(p) {
  await fs.rm(p, { recursive: true, force: true });
}

async function copyFile(rel) {
  const from = path.join(srcRoot, rel);
  const to = path.join(dstRoot, rel);
  await fs.mkdir(path.dirname(to), { recursive: true });
  await fs.copyFile(from, to);
}

async function walk(dir) {
  const out = [];
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) {
      const relDir = path.relative(srcRoot, full).split(path.sep).join("/");
      const segments = relDir.split("/");
      if (segments.some((s) => EXCLUDE_DIRS.has(s))) continue;
      out.push(...(await walk(full)));
    } else if (e.isFile()) {
      out.push(full);
    }
  }
  return out;
}

async function main() {
  await rimraf(dstRoot);
  await fs.mkdir(dstRoot, { recursive: true });

  const copied = [];
  const seen = new Set();

  for (const tree of INCLUDE_TREES) {
    const abs = path.join(srcRoot, tree);
    const files = await walk(abs);
    for (const file of files) {
      const rel = path.relative(srcRoot, file).split(path.sep).join("/");
      if (EXCLUDE_FILES.has(rel)) continue;
      if (seen.has(rel)) continue;
      seen.add(rel);
      await copyFile(rel);
      copied.push(rel);
    }
  }

  for (const rel of INCLUDE_FILES) {
    try {
      await copyFile(rel);
      copied.push(rel);
    } catch {}
  }

  // Public index for the managed package.
  const indexPath = path.join(dstRoot, "index.ts");
  await fs.writeFile(
    indexPath,
    `// Auto-generated by cms-distribution/scripts/sync-managed.mjs\n` +
      `// Source of truth for the reusable Child CMS surface.\n` +
      `export { default as AdminShell } from "./pages/admin/AdminShell";\n` +
      `export { default as AdminDashboard } from "./pages/admin/AdminDashboard";\n` +
      `// Add additional re-exports here as the managed surface stabilises.\n`,
  );
  copied.push("index.ts");

  console.log(`Synced ${copied.length} files into cms-distribution/managed/src/cms-managed`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
