// Auto-generated by cms-distribution/scripts/sync-managed.mjs
// Source of truth for the reusable Child CMS surface.
export { default as AdminShell } from "./pages/admin/AdminShell";
export { default as AdminDashboard } from "./pages/admin/AdminDashboard";
// Add additional re-exports here as the managed surface stabilises.
