// Setup Wizard — generates a copy-paste bootstrap snippet for each child site.
// Admin enters the child's site_id (and optional metadata), and gets:
//   1. `src/cms-bootstrap.ts` content
//   2. The `.env` lines for VITE_PARENT_CMS_URL and VITE_SITE_ID
//   3. Instructions for wiring into the child's main.tsx

import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card } from "@/components/ui/card";
import { Wand2, Copy, Check } from "lucide-react";
import { toast } from "sonner";

const PARENT_RELEASE_URL = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/cms-release`;

export default function AdminSetupWizard() {
  const [siteId, setSiteId] = useState("");
  const [siteName, setSiteName] = useState("");
  const [siteUrl, setSiteUrl] = useState("");
  const [copied, setCopied] = useState<string | null>(null);

  const bootstrap = useMemo(() => `// src/cms-bootstrap.ts — generated by Parent CMS Setup Wizard
// Do not edit by hand. Re-generate from /admin/setup-wizard if anything changes.
import { bootstrapCmsCore } from "@/cms-core/bootstrap";

export const cmsCore = await bootstrapCmsCore({
  parentReleaseUrl: "${PARENT_RELEASE_URL}",
  siteId: "${siteId || "REPLACE_WITH_SITE_ID"}",
  siteName: ${JSON.stringify(siteName || null)},
  siteUrl: ${JSON.stringify(siteUrl || null)},
  // Optional: wire this to apply parent migrations against the child's own Cloud DB.
  // runMigration: async (step) => { /* execute step.payload */ },
});

if (cmsCore.sdkLoaded) {
  // eslint-disable-next-line no-console
  console.info("[cms-core] engine loaded:", cmsCore.version);
}
`, [siteId, siteName, siteUrl]);

  const mainSnippet = `// src/main.tsx — add this BEFORE rendering your app
import "./cms-bootstrap"; // boots & heartbeats on every load

import { createRoot } from "react-dom/client";
import App from "./App.tsx";
import "./index.css";

createRoot(document.getElementById("root")!).render(<App />);`;

  const copy = async (text: string, key: string) => {
    await navigator.clipboard.writeText(text);
    setCopied(key);
    toast.success("Copied");
    setTimeout(() => setCopied(null), 1500);
  };

  return (
    <div className="space-y-6 max-w-3xl">
      <header>
        <h1 className="font-display text-3xl flex items-center gap-2">
          <Wand2 className="w-7 h-7" /> Child setup wizard
        </h1>
        <p className="text-muted-foreground text-sm mt-1">
          Generate the bootstrap snippet for a child site. Paste the output into the child's Lovable project — once installed, that child receives every future engine release automatically.
        </p>
      </header>

      <Card className="p-5 space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <Label>Child site ID (unique)</Label>
            <Input value={siteId} onChange={(e) => setSiteId(e.target.value)} placeholder="acme-marketing" />
          </div>
          <div>
            <Label>Display name (optional)</Label>
            <Input value={siteName} onChange={(e) => setSiteName(e.target.value)} placeholder="Acme Marketing Site" />
          </div>
          <div className="md:col-span-2">
            <Label>Site URL (optional)</Label>
            <Input value={siteUrl} onChange={(e) => setSiteUrl(e.target.value)} placeholder="https://acme.example.com" />
          </div>
        </div>
      </Card>

      <Snippet label="1. src/cms-bootstrap.ts" code={bootstrap} copied={copied === "bootstrap"} onCopy={() => copy(bootstrap, "bootstrap")} />
      <Snippet label="2. src/main.tsx (add the import)" code={mainSnippet} copied={copied === "main"} onCopy={() => copy(mainSnippet, "main")} />

      <Card className="p-5">
        <h2 className="font-display text-lg mb-2">Next steps in the child project</h2>
        <ol className="list-decimal pl-5 space-y-1 text-sm text-muted-foreground">
          <li>Create <code>src/cms-bootstrap.ts</code> with the snippet above.</li>
          <li>Add the import line to <code>src/main.tsx</code>.</li>
          <li>Copy the entire <code>src/cms-core/</code> folder from this parent CMS into the child (one-time scaffold; future updates ship as the SDK bundle).</li>
          <li>Reload the child site. It will appear in <strong>Installations</strong> within seconds.</li>
        </ol>
      </Card>
    </div>
  );
}

function Snippet({ label, code, copied, onCopy }: { label: string; code: string; copied: boolean; onCopy: () => void }) {
  return (
    <Card className="p-0 overflow-hidden">
      <div className="flex items-center justify-between border-b px-4 py-2 bg-muted/30">
        <span className="text-sm font-medium">{label}</span>
        <Button size="sm" variant="ghost" onClick={onCopy}>
          {copied ? <Check className="w-4 h-4 mr-1" /> : <Copy className="w-4 h-4 mr-1" />}
          {copied ? "Copied" : "Copy"}
        </Button>
      </div>
      <pre className="p-4 text-xs overflow-x-auto bg-background"><code>{code}</code></pre>
    </Card>
  );
}
